config/routes.rb
Rails.application.routes.draw do
   resources :tweets do
     resources :comments
   end
   resources :users
   root 'tweets#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new 
        @tweet= Tweet.find(params[:tweet_id])
        @comment= @tweet.comments.new
    end
    def create 
        @tweet= Tweet.find(params[:tweet_id])
        comment=@tweet.comments.new(comment_params)
        comment.save
        redirect_to tweet_path(@tweet)
    end


    private

    def comment_params
        params.require(:comment).permit(:id,:content,:tweet_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@hola = "hola estoy funcionando "
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	
	def new
		@tweet = Tweet.new 
		@user = User.new
	end
	def create
		@tweet = Tweet.new(tweet_params)
		if @tweet.save
			redirect_to @tweet
		else
			render :new
		end
	end
	
	def index
		@tweets = Tweet.all 
	end
	def show
		@tweet = Tweet.find(params[:id])
		@comments = @tweet.comments.all
	end
	def edit
		@tweet = Tweet.find(params[:id]) 
	end
	def update
		@tweet = Tweet.find(params[:id])
		@tweet.update(tweet_params)
		redirect_to @tweet
	end
	def destroy	
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
		redirect_to tweets_path
	end
	
	private
	def tweet_params 
		params.require(:tweet).permit(:message,:title, :user_id) #parametes form
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 def index
    @users = User.all
  end
  def new
        @user = User.new
  end
  def create
        @user= User.new(user_params)
        @user.save
        redirect_to users_path
  end
   def edit
       @user = User.find(params[:id])
   end
   def update
       @user = User.find(params[:id])
       @user.update(user_params)
       redirect_to users_path
   end
   def show
     @user=User.find(params[:id])
     @tweets=@user.tweets.all
   end
   def destroy
        @user =  User.find(params[:id])
        @user.destroy
        redirect_to users_path
   end
   def user_params
        params.require(:user).permit(:name, :email )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%=link_to "Crear comentario", new_tweet_comment_path(@tweet)%>

<%= form_for  [@tweet, @comment] do |f| %>
<%=f.label :content, "Comentario" %>
<%=f.text_field :content %>
<%=f.submit %>
<%end%>

app/views/home/index.html.erb
<h1>este es mi index</h1>

<p> <%= @hola %></p>

app/views/layouts/_forms.html.erb
<div class= 'starter-template'></div>
<%= form_for @tweet do |t| %>
<p>
	<%=t.label :title%><br>
	<%=t.text_field :title %>
</p>
<p> 	
	<%= t.label :message %><br>
	<%= t.text_field :message%>
</p>

<p>
	<%= t.submit %>
</p>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
   <%= link_to "TWEETER", users_path, id: "logo" %>
   <nav>
     <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Home",   '#' %></li>
       <li><%= link_to "Help",   '#' %></li>
       <li><%= link_to "Log in", '#' %></li>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
	<%=render 'layouts/header'  %>

<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<h1>Editar Tweets</h1>

 <%= render 'layouts/forms'  %>
<%= link_to 'Atras', users_path %>

app/views/tweets/index.html.erb
<h1>Lista de tweet's</h1>
<%= link_to "Nuevo Tweet", new_tweet_path %>
<ul>
    <% @tweets.each do |t|%>
    
    	<li> 
     <h3> <strong> <%= t.title  %> </strong> </h3>
        <p> <%= t.message %> </p>
        <%= link_to 'Editar', edit_tweet_path(t) %>
      	<%= link_to 'Eliminar', t, method: :delete, data: { confirm: 'estas seguro ?' } %> 
      	<%=link_to "Detalles", t %></li>
          <ol>
            <% @comments = t.comments.all  %>
              <% @comments.each do |comment| %>
              <li><%= comment.content  %></li>
              <% end %>
          </ol>
   
    <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>Crear tweets</h1>

<%= render 'layouts/forms' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
 <h1>Tweet</h1>

	<h3> <strong><%=@tweet.title %></strong></h3>
 <p>
 	<%= @tweet.message  %>
 </p>
 <%=link_to "Crear comentario", new_tweet_comment_path(@tweet)%>
 <ul>
    <% @comments.each do |comment|%>
        <li>
            <%=comment.content%>
        </li>
    <%end%>
</ul>

 <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/edit.html.erb
<h1>Editar usuarios</h1>

<%= form_for @user do |u| %>
<p>
	<%=u.label :email%><br>
	<%=u.text_field :email %>
</p>

	<%= t.submit %>
</p>

<% end %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Lista de usuarios</h1>
<%= link_to "Nuevo usario", new_user_path %>
<ul>
    <% @users.each do |t|%>
    
    	<li> 
        <p> <%= t.email %> </p>
        <%= link_to 'Editar', edit_user_path(t) %>
      	<%= link_to 'Eliminar', t, method: :delete, data: { confirm: 'estas seguro ?' } %> 
      	<%=link_to "Detalles", t %></li>
          <ol>
            <% @tweets = t.tweets.all  %>
              <% @tweets.each do |tweet| %>
              <li><%= link_to tweet.message , tweet_path(t)  %></li>
              <% end %>
          </ol>
   
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Crear usuarios</h1>

<%form_for @user do |u| %>
<p>
	<%=u.label :email%><br>
	<%=u.text_field :email %>
</p>
<p>

	<%= u.submit %>
</p>

<% end %>
<%= link_to 'Back', users_path %>